# Generated by Django 3.2 on 2022-12-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('unique_code', models.IntegerField(unique=True)),
                ('size', models.CharField(choices=[('a', 10), ('b', 20), ('c', 30)], max_length=1)),
                ('quality', models.CharField(choices=[('h', 'high'), ('m', 'medium'), ('l', 'low')], max_length=1)),
            ],
        ),
    ]
